name: NEBULA CLI Demo
on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  demo:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy matplotlib
        
    - name: Run NEBULA Demo
      run: |
        python nebula_cli.py demo
        
    - name: Run NEBULA Query Example
      run: |
        python nebula_cli.py query "¿Cómo se pueden optimizar los grandes modelos de lenguaje usando física óptica y cuántica?"
        
    - name: Generate Visualization
      run: |
        python nebula_cli.py visualize --output nebula_visualization.png
        
    - name: Upload Visualization
      uses: actions/upload-artifact@v3
      with:
        name: nebula-visualization
        path: nebula_visualization.png
